FROM node:20-alpine

WORKDIR /app

# Копируем package файлы
COPY package*.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Устанавливаем глобально Nest CLI
RUN npm install -g @nestjs/cli

# Открываем порты для приложения и отладки
EXPOSE 3000 9229

# Запускаем в режиме разработки
CMD ["npm", "run", "start:dev"]